// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// events
export const EVENT_REQUEST = 'EVENT_REQUEST';
export const EVENT_RESPONSE = 'EVENT_RESPONSE';
export const EVENT_FAILED = 'EVENT_FAILED';
export const EVENT_ENABLE_LOADER = 'EVENT_ENABLE_LOADER';
export const EVENT_DISABLE_LOADER = 'EVENT_DISABLE_LOADER';